version: '3.7'

services:
  nest:
    container_name: nest-container
    build:
      context: ./backend/
      target: '${TARGET}'
    volumes:
      - ./backend/:usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${API_PORT}:${API_PORT}'
      - '5431:5431'
      - '9229:9229'
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/data/postgres
    networks:
      - webnet
    env_file:
      - .env
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${POSTGRES_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - webnet
    env_file:
      - .env

  recognition:
    container_name: recognition
    image: alphacep/kaldi-en:latest
    ports:
      - '2700:2700'
    networks:
      - webnet
    env_file:
      - .env

networks:
  webnet:
    driver: bridge
    name: webnet

volumes:
  postgres:
  pgadmin:
